default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind  
stages:          # List of stages for jobs, and their order of execution
  - build
  - deliver

build-image-job:
  stage: build
  tags:
    - build
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


    # Iterate over directories and build images
    - |
      for dir in */; do
        dir=${dir%*/} # Remove trailing slash
        image_name="$CI_REGISTRY/manos972/tp_fil_rouge/${dir}:v1.1"
        docker build -t $image_name ./$dir
        docker push $image_name
      done

deliver-job:
  stage: deliver
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context Manos972/k8s-connection:k8s-connection
    - kubectl get pods
    - kubectl apply -f ./infra/k8s
    - sleep 10
    - kubectl get pods
    - sleep 10
    - kubectl get svc
    - kubectl get pods
