stages:          # List of stages for jobs, and their order of execution
  - build
  - deliver

build-image-job:
  stage: build
  tags:
    - build
  image: docker:24.0.5 
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - chmod +x iterateFolder.sh
    - ./iterateFolder.sh

deliver-job:
  stage: deliver
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context Manos972/k8s-connection:k8s-connection
    - kubectl get pods
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
    - sleep 10
    - kubectl get ingress
    - kubectl apply -f ./infra/k8s
    - sleep 10
    - kubectl get pods
    - sleep 5
    - kubectl get svc
    - sleep 35
    - kubectl get pods
