default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind  
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-image-job:
  stage: build
  tags:
    - build
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/client .
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/event-bus .
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/posts .
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/comments .
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/moderation .
    - docker build -t $CI_REGISTRY/manos972/tp_fil_rouge/query .
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/client:latest
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/event-bus:latest
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/posts:latest
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/comments:latest
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/moderation:latest
    - docker push $CI_REGISTRY/manos972/tp_fil_rouge/query:latest

deploy-job:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context test6781146/k8s-connection:k8s-connection
    - kubectl get pods

