apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-srv
  template:
    metadata:
      labels:
        app: client-srv
    spec:
      containers:
        - name: cicd_client-srv
          image: registry.gitlab.com/manos972/tp_fil_rouge/client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: app-secret
