apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus-srv
  template:
    metadata:
      labels:
        app: event-bus-srv
    spec:
      containers:
        - name: cicd_event-bus-container
          image: registry.gitlab.com/manos972/tp_fil_rouge/event-bus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4005
      imagePullSecrets:
        - name: app-secret
