apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation-srv
  template:
    metadata:
      labels:
        app: moderation-srv
    spec:
      containers:
        - name: cicd-moderation-container
          image: registry.gitlab.com/manos972/tp_fil_rouge/moderation:v1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4003
      imagePullSecrets:
        - name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation-srv
  ports:
    - protocol: TCP
      port: 4003
